### ISSUE TITLE
Update to SS4

### ISSUE THREAD

**Issue by wernerkrauss** [nomidi/silverstripe-webp-image#1]
As webp seems to become more supported and more important for SEO, are there any plans to update this module to SS4?

**Comment by ArminEden** [comment]
Hi,

Yes, plans are to update it as soon as possible. Probably not before the start of next year.

**Comment by huub-l** [comment]
Hi, do you have concrete plans to update to SS4 any time soon?

**Comment by nomidi** [comment]
Hi, yes :). I hope an ss4 Version is ready next week

**Comment by huub-l** [comment]
Ok, awsome!

**Comment by sheadawson** [comment]
Seems this is done and can be closed?
